name: flutter_study_2021
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  path_provider: ^2.0.2 # 文件管理
  dio: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  # 使用 flutter 默认包含的 Material Design 字体图标
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/json/text_user_data.json
    - assets/json/text_user_data_root_bundle.json
    - assets/images/background.jpg
    - assets/images/dpi_test_icon.jpg
    - packages/flutter_study_2021/images/package_icon.jpg
    - assets/images/icon_image_test.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: testFontFamily
      fonts:
        - asset: assets/fonts/test_fonts.ttf
    - family: pacakgeFontFamily
      fonts:
        - asset: packages/flutter_study_2021/fonts/test_package_font.ttf
