name: flutter_study_2021
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # 模块化
  zinc_package:
    path: ./zinc_package

  # 第三方库
  cupertino_icons: ^1.0.2
  path_provider: ^2.0.2 # 文件管理

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  # 使用 flutter 默认包含的 Material Design 字体图标
  uses-material-design: true

  # 添加静态资源
  assets:
    - assets/json/text_user_data.json
    - assets/json/text_user_data_root_bundle.json
    - assets/images/background.jpg
    - assets/images/dpi_test_icon.jpg
    - packages/flutter_study_2021/images/package_icon.jpg
    - assets/images/icon_image_test.png
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # 添加字体
  fonts:
    - family: testFontFamily
      fonts:
        - asset: assets/fonts/test_fonts.ttf
    - family: pacakgeFontFamily
      fonts:
        - asset: packages/flutter_study_2021/fonts/test_package_font.ttf
